#install.packages("lubridate")
library(lubridate)
library(grDevices)
data<-read.table(file="household_power_consumption.txt",sep=";",header = T,na.strings = "?")
datetime<-dmy(data$Date)+hms(data$Time)
data<-cbind(data,datetime)
data<-subset(x = data,subset = (datetime > "2007-02-01 00:00:00 UTC" & datetime < "2007-02-03 00:00:00 UTC"))
png(filename = "plot1.png", width = 480, height = 480, units = "px")
hist(data$Global_active_power,col=rgb(253,51,37,maxColorValue=253),xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.off()
