install.packages("lubridate")
library(lubridate)
data<-read.table(file="household_power_consumption.txt",sep=";",header = T,na.strings = "?")
datetime<-dmy(data$Date)+hms(data$Time)
data<-cbind(data,datetime)
data<-subset(x = data,subset = (datetime > "2007-02-01 00:00:00 UTC" & datetime < "2007-02-03 00:00:00 UTC"))
Sys.setlocale("LC_TIME","en_US.UTF-8")
png(filename = "plot2.png", width = 480, height = 480, units = "px")
plot(data$datetime,data$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.off()
